// Package genshipped turns drivers/BUNDLED_SOURCE.json into the driver names
// this build ships with.
//
// The pin is already the answer to "which drivers does FTW bundle" — it is
// what scripts/sync-bundled-drivers.sh fetches from and what CI counts the
// fetched files against. Compiling it in is what makes the fleet ping's claim
// true: the set is decided when the binary is built, so no file on a running
// box and no field in its config can add a name to it.
//
// Run it with `go generate ./internal/fleetping/...`.
package genshipped

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"regexp"
	"sort"
)

// driverID is what a bundled driver may be called. Deliberately narrow: this
// list becomes the set of names allowed to leave a house, so a pin that grew a
// path, a space or a capital letter is a mistake to stop at build time rather
// than a string to pass on.
var driverID = regexp.MustCompile(`^[a-z0-9][a-z0-9_]*$`)

// Generate renders the name list. Exported and byte-deterministic so the drift
// test can re-run it in memory and compare, rather than shelling out.
func Generate(raw []byte) ([]byte, error) {
	var pin struct {
		Drivers []string `json:"drivers"`
	}
	if err := json.Unmarshal(raw, &pin); err != nil {
		return nil, fmt.Errorf("parse the bundled-driver pin: %w", err)
	}
	if len(pin.Drivers) == 0 {
		return nil, fmt.Errorf("the bundled-driver pin lists no drivers")
	}

	names := make([]string, 0, len(pin.Drivers))
	seen := make(map[string]bool, len(pin.Drivers))
	for _, name := range pin.Drivers {
		if !driverID.MatchString(name) {
			return nil, fmt.Errorf("%q is not a driver id", name)
		}
		if seen[name] {
			return nil, fmt.Errorf("%q is listed twice", name)
		}
		seen[name] = true
		names = append(names, name)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString("// Code generated by genshipped from drivers/BUNDLED_SOURCE.json. DO NOT EDIT.\n\n")
	b.WriteString("package fleetping\n\n")
	b.WriteString("// shippedDrivers are the driver types bundled with this build.\n")
	b.WriteString("//\n")
	b.WriteString("// An array rather than a slice, so it is fixed in every sense: the length\n")
	b.WriteString("// is part of the type and nothing can append to it at run time.\n")
	fmt.Fprintf(&b, "var shippedDrivers = [%d]string{\n", len(names))
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q,\n", name)
	}
	b.WriteString("}\n")

	return format.Source(b.Bytes())
}
