// Code generated by gencontract from contract/registry.yaml. DO NOT EDIT.

package apiauth

// Roles an enrolment can hold. Hand-writing one of these strings is
// what the registry exists to stop, and a role is the one name here
// that decides whether a phone may change anything.
const (
	// RoleOwner — Owner.
	RoleOwner = "owner"
	// RoleViewer — Viewer.
	RoleViewer = "viewer"
)

// RoleScopes is what each role carries, with '*' already expanded.
// A role is a projection over scopes and never a replacement for them,
// so this is the only place the projection is written down.
var RoleScopes = map[string][]string{
	RoleOwner: {
		"ftw.live.read",
		"ftw.history.read",
		"ftw.plan.read",
		"ftw.health.read",
		"ftw.assets.read",
		"ftw.dispatch.write",
		"ftw.mode.write",
		"ftw.members.read",
		"ftw.members.write",
	},
	RoleViewer: {
		"ftw.live.read",
	},
}
